// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCwa2QCKSlgyKb8enh_Xp-Q3kR6tBZvNg',
    appId: '1:6149966850:web:c1825775b7ce8881fceb1b',
    messagingSenderId: '6149966850',
    projectId: 'voyease-83b9b',
    authDomain: 'voyease-83b9b.firebaseapp.com',
    storageBucket: 'voyease-83b9b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpiLaWgifh2NTuzMbCyD4CY3SjEmJHmhs',
    appId: '1:6149966850:android:a7887290d69202cbfceb1b',
    messagingSenderId: '6149966850',
    projectId: 'voyease-83b9b',
    storageBucket: 'voyease-83b9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkJONoI8aoFCvO1Shly44Q0q7HHWZuPuw',
    appId: '1:6149966850:ios:f7fd0c7a3d083127fceb1b',
    messagingSenderId: '6149966850',
    projectId: 'voyease-83b9b',
    storageBucket: 'voyease-83b9b.appspot.com',
    iosBundleId: 'com.example.voyeaseFrontend',
  );
}
